# Generated by Django 3.1.1 on 2020-09-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20200923_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['name']},
        ),
    ]
